# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-86410344-2'

menu:
- {name: 'Blog', url: 'blog'}
# - {name: 'About', url: 'menu/about.html'}
- {name: 'Tags', url: 'menu/tags.html'}
- {name: 'Contacts', url: 'menu/contacts.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'telegram', link: 'https://t.me/maximgorbatyuk', title: 'Contact me in Telegram'}
- {icon: 'github', link: 'https://www.github.com/maximgorbatyuk', title: 'View my repositories'}
- {icon: 'instagram', link: 'https://instagram.com/maxim.gorbatyuk', title: 'Follow me on instagram'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/', title: ''}
- {icon: 'envelope', link: 'mailto:maxim.gorbatyuk@outlook.com', title: 'Contact me via email'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
